development: &default
  access_key_id: ENV['S3_ACCESS_KEY_ID']
  secret_access_key: ENV['S3_SECRET_ACCESS_KEY']
  bucket: ENV['S3_BUCKET_NAME_DEVELOPMENT']
  simple_db_consistent_reads: false

production:
  access_key_id: ENV['S3_ACCESS_KEY_ID']
  secret_access_key: ENV['S3_SECRET_ACCESS_KEY']
  bucket: ENV['S3_BUCKET_NAME_PRODUCTION']
  simple_db_consistent_reads: true